### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [cwh94/model_loads#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.4. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary model-loads -w /tmp/ext model-loads==0.2.4
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting model-loads==0.2.4
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/cc3/cef35b1e18d68/model-loads-0.2.4.tar.gz (7.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-qooembld/model-loads/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-qooembld/model-loads/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-qooembld/model-loads/pip-egg-info
         cwd: /tmp/pip-wheel-qooembld/model-loads/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-qooembld/model-loads/setup.py", line 10, in <module>
        with open(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'README.md'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-qooembld/model-loads/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by chaow94** [comment]
Thanks a lot, I will update soon in next version.
